### ISSUE TITLE
Minor change needed

### ISSUE THREAD

**Issue by hopesunknown** [learn-co-curriculum/react-hooks-react-app-example#13]
### Canvas Link

https://learning.flatironschool.com/courses/4566/assignments/161323?module_item_id=345763

### Concern

Where it says _"Importing, Exporting, and the Dependency Tree
There are two other sections in the App.js file we haven't touched on:"_ it isn't referring to App.js but index.js.

**Comment by AlveeM** [comment]
Hello, and thank you for submitting an issue. 

It seems the lesson is referencing the `App.js` file [here](https://github.com/learn-co-curriculum/react-hooks-react-app-example/blob/master/src/components/App.js#L1).

The two sections referenced are the import statements (lines 1-3) and the export statements (line 21). 

The `import App from "./App";` at the end of the section is in the `index.js` file.

Thanks again for submitting an issue and happy coding!
