### ISSUE TITLE
All tests failing despite correct code

### ISSUE THREAD

**Issue by jacoblogan98** [learn-co-curriculum/react-hooks-react-app-example#17]
### Canvas Link

https://learning.flatironschool.com/courses/5285/assignments/172306?confetti=true&submitted=0

### Concern

I had a student come to the TC support for failing tests despite his code being exactly similar to the solution branch. I was not able to find any difference between his code and the solution code, and I couldn't find any issues in the test file either. I wish I had the issue pinpointed but I have no clue what was causing this issue.

**Comment by lizbur10** [comment]
Hi @jacoblogan98 - I'm going to go ahead and close this issue. If you discover that there's an issue with the lab setup, please let us know.

Thanks 💙
